### PR TITLE
Portuguese translation of HTML lessons 2 and 3

### PR DESCRIPTION
**Pull request by laszpio**
First attempt to translate lessons 2 and 3. It needs a revision of native Brazilian Portuguese developer.

### CODE REVIEW

**Comment by despo** [comment]
That's awesome. Should I tweet as we discussed?

**Comment by laszpio** [comment]
@despo yes please :-)

**Comment by matyikriszta** [comment]
hey @laszpio, did you find anyone to help you with proofreading these? do let us know if you need more support with this

**Comment by laszpio** [comment]
hey @matyikriszta, @talitanoguchi twitted me they started to work on it but I have no idea on progress as they didn't come back to me :-(

**Comment by talitanoguchi** [comment]
@laszpio @matyikriszta @despo we merged some stuff in the github. not all. we did 4 lessons of html, 3 of ruby and more 3 of other language

**Comment by miguelpeixe** [comment]
hey guys, this is where we are pushing our translation
https://github.com/codeira/tutorials

looks like we might be doing the same thing!

**Comment by iteles** [comment]
@miguelpeixe Are you guys going to PR your translations back to @codebar's main repo?
I've offered to proof-read PT translations but would rather make sure I'm proof-reading the right version!

**Comment by matyikriszta** [comment]
@miguelpeixe @talitanoguchi are you guys working together? I'm trying to sort this out so we actually make some progress on it. If so, could you issue a PR back to the main codebar repo so eveything is in one place? @iteles thanks for looking into this, let me sort out who did what and when I know which one is the final version I'll let you know. Thanks for helping :+1:

**Comment by iteles** [comment]
@matyikriszta No problem, let me know when you need my help :blush:

**Comment by iteles** [comment]
@matyikriszta @laszpio @miguelpeixe I suggest that if this PR isn't going to go ahead, we **close it**, otherwise it will give the impression that this is in progress and hinder getting help from other sources ✨ 

Also, it's been in my [PR mentions](https://github.com/pulls/mentioned) for 2 years and I'm ready to clean house 🏡 😛

**Comment by KimberleyCook** [comment]
@iteles I'm happy to close this and if need be, open it again.

**Pull request closed without merging**
