### PR TITLE
Adding JS tutorial examples Working on issue:#229

### PR DESCRIPTION
**Pull request by martyjg**
I added real-world and beginner-friendly examples in the javascript tutorial markdown files for the if, while and for tutorials. @codebar @ladieswhocode

### CODE REVIEW

**Comment by Charlotteis** [comment]
Hi @martyjg! I have a small suggestion. Do you see how when we talk about while loops we wrap them in quotes like backwards single quotes? That shows that `while` is a piece of code. If you do that for when you mention an `if` statement, it'd be easier to tell when you are talking about an `if` statement, or are just using the word "if". I may not have explained this so well, so feel free to get me to explain it in person!

**Comment by martyjg** [comment]
Heyy that sounds cool. I added backticks to wherever I mentioned `if` or `for` like that in the examples.

**Comment by KimberleyCook** [comment]
:+1:

**Comment by Charlotteis** [comment]
Thanks!

**Pull request merged**
