### PR TITLE
Dependancies: Lock down with Gemfile

### PR DESCRIPTION
**Pull request by lpil**
Let's ensure everyone is on the correct version :)

### CODE REVIEW

**Comment by lpil** [comment]
'ello? :)

**Comment by lpil** [comment]
ping @deniseyu

**Comment by deniseyu** [comment]
@lpil this requires everyone to be using Bundler 1.10+, you sure this won't cause version control issues?

**Comment by lpil** [comment]
It doesn't- you can continue to not use bundler and only use gem and jekyll without `bundle exec`. However, this is a bad idea, as everyone will be using different versions of the compiler. We should be using the same one in development as in production, especially the one in production is *not* the latest version.

As for the bundler version, everyone should be using the latest version. What version control issues are you worried about?

**Comment by fanaugen** [comment]
:+1: to this change. It’s a good idea to use the same version of Jekyll that GitHub runs.

But it should come with an update to the **Contributing** section of the README, mentioning `bundle install`

**Comment by lpil** [comment]
Good point. I've updated the getting started instructions.

Good to go?

**Comment by matyikriszta** [comment]
thanks @lpil :+1:

**Pull request merged**
