### PR TITLE
updated README to include links to Codebar Slack

### PR DESCRIPTION
**Pull request by ma3east**
during @codebar and @ladieswhocode pullrequest event

### CODE REVIEW

**Comment by Charlotteis** [comment]
Hi @ma3east! That link directly links to the "uncodebar" channel on the Slack, which I don't think people want to go to as their first channel? How about `https://codebar.slack.com/messages/general/`. Good pull request :sparkles:.

**Comment by KimberleyCook** [comment]
@ma3east Hey, thank you for this PR but could the codebar be a little c please :)

**Comment by ma3east** [comment]
Hi @KimberleyCook  and @Charlotteis , have updated the link to the general channel, and changed to a lowercase c, please check and merge if necessary.  Thanks, Andrea.

**Comment by KimberleyCook** [comment]
All merged :+1:

**Pull request merged**
