### PR TITLE
Writing PHP in a free Web based IDE

### PR DESCRIPTION
**Pull request by eddiejaoude**
No need to install PHP on your local machine. In a few simple steps and minutes you can have all the **CLI** and **Webserver** functionality by using a free Web based IDE (Cloud9IDE).

### CODE REVIEW

**Comment by jonnyarnold** [comment]
Hi there. First time commenter, to take everything I say with a pinch of salt :)

I would suggest giving the student the option:

- Some students will want to get writing code straight away; don't care how or where their code runs; and will always have an Internet connection when developing. For these people, Cloud9 is a good choice.
- Some students want to know how everything works: they want to learn about servers and what they do, and they want to learn it as they go along. For these people, manual installation would be more rewarding.

Would you be able to reinstate the manual installation option and add your Cloud9 instructions alongside the manual installation instructions?

**Comment by eddiejaoude** [comment]
Both good points.

> Would you be able to reinstate the manual installation option and add your Cloud9 instructions alongside the manual installation instructions?

I think it would be too confusing to have both in the same lesson. I think the online IDE lesson / step should be optional.

**Comment by jonnyarnold** [comment]
Fair point!

**Comment by eddiejaoude** [comment]
Thanks for your feedback though, I will make an update, to clearly make lesson1 optional

**Comment by despo** [comment]
@eddiejaoude looks good but I think lesson 1 can be entirely substituted by pointing the students to the i9 getting started docs https://docs.c9.io/docs/getting-started, preferably from the [index page](tutorials.codebar.io) similarly to how we suggest nitrous  for ruby, so it's hard to miss in case they are not up for any local setup.

screen shot 2015-10-15 at 14 50 43

**Comment by eddiejaoude** [comment]
> I think lesson 1 can be entirely substituted by pointing the students to the i9 getting started docs https://docs.c9.io/docs/getting-started

Sure. I will make the change.

**Comment by eddiejaoude** [comment]
@despo made the suggested changes, please review again :smile:

**Comment by despo** [comment]
Thanks @eddiejaoude :+1:

**Pull request merged**
