### PR TITLE
PHP Tutorial lesson 2

### PR DESCRIPTION
**Pull request by kodikos**
This is to add a 2nd part to the PHP tutorial. I have also tweaked other areas of the PHP tutorial area:
* Moved using PHP into its own page of simple installation and usage (a more complex discussion will follow)
* Addition of lesson 2 page on values and variables
* Tweaks to lesson 1 to point out to the simple guide
* Removing refs to cloud9 (no longer free, or simple to use!)
* Updated main index page to advertise tutorial 2

### CODE REVIEW

**Comment by brunogirin** [comment]
I like the new page that explains how to install PHP. Will that install 5.x or 7.x and is there any need to mention version numbers at any point?

**Comment by kodikos** [comment]
Thanks for looking in, @brunogirin :) You raise an interesting point. I was linking to the PHP instructions thinking it would point to latest installs in a system-dependent way with package managers, but they appear to be mainly showing how to install the 5.x version.. boo :( I think I'll need to add some explicit notes to get everyone installing 7, but might need help on the mac instructions (would brew instructions be sufficient?). phpFiddle is 7.0.x at time of writing. Generally, I don't think the tutorials yet hit any differences, but as I'm bit of a newbie to 7, I'll try to keep an eye out. I wanted to keep the tutorials relatively simple, so hopefully won't come across too much that's incompatible, and I'll always go with the 7.x way of doing things, and add a note about assuming this.

**Comment by KimberleyCook** [comment]
@kodikos @brunogirin am I good to merge this in?

**Comment by brunogirin** [comment]
@KimberleyCook yes you are, thanks!

**Comment by kodikos** [comment]
The installer instructions are not ideal, but it's more a problem with the PHP documentation than ours. It probably also needs a rebase with master as it mods the tutorials index. Thanks @KimberleyCook

**Comment by kodikos** [comment]
I've just rebased with master. Found out that macs (high sierra+) already have PHP7 installed :)

**Review by KimberleyCook — APPROVED** [review]
Merging, thank you so much for this @kodikos and apologies for the delay in getting it merged in.

**Pull request merged**
