### PR TITLE
updated dev tools and box model section in html lesson 3

### PR DESCRIPTION
**Pull request by globalavocado**
added new screenshot for Chrome Devtools, amended text. Added new animated image for box model, by example of BBC News website, amended text accordingly.

### CODE REVIEW

**Comment by KimberleyCook** [comment]
@globalavocado Nice update, thank you. 

Just a little typo amend though. In the last sentence could you make it "In the below example" rather than "In below example" please.

**Comment by globalavocado** [comment]
would you also be happy with "In the example below..."?

**Comment by KimberleyCook** [comment]
@globalavocado Yeah or that

**Comment by KimberleyCook** [comment]
:+1:

**Pull request merged**
