### PR TITLE
Lesson 4 updates

### PR DESCRIPTION
**Pull request by samsworldofno**
* ✓ use jquery from cdn in code snippet download
* ✓ add example requests
* ✓ improve introduction sentence
* ✓ bin the git stuff
* ✓ simplify the http verbs - GET/POST only, and tidy up language about "how actions are performed"
* ✓ remove "always use async"
* ✓ AJAX can be used for JSON
* ✓ integrate the xhr and json parsing
* ✓ slightly expanded description of JSON and link to specification
* ✓ better explanation of what the 'partial response' is - suggest which fields to use
* ✓ make json snippet valid by removing ellipsis
* ✓ start with synchronous - remove "otherwise section"
* ✓ happy path first with first response - error as next section
* ✓ remove publishing to github
* ✓ add "well done you've finished" after the first task is done
* ✓ add ajax as a "bonus" - easy to add in
* ✓ move jquery to exercise 2

### CODE REVIEW

**Comment by samsworldofno** [comment]
adding @jkbits1

**Comment by matyikriszta** [comment]
@samsworldofno @jkbits1 this looks really good, a few comments on my part:

- explain what current server uptime is. This sounds a bit too technical to me
- explain where to put the curl command. Some people might've not done the command line tutorial or might not know what `curl` is
- when we are talking about passing things to github, can we be explicit and say passing things to the github API?

otherwise looks good for me :)

**Comment by samsworldofno** [comment]
@matyikriszta thanks for the feedback - I've made some changes, let me know what you think :)

**Comment by KimberleyCook** [comment]
@samsworldofno One other little amend I want to add an objectives and goal section at the top of each of the tutorials. Like this http://tutorials.codebar.io/html/lesson1/tutorial.html

Could you add that please. Once done I'll merge :)

**Comment by samsworldofno** [comment]
@KimberleyCook done; @jkbits1 you may want to check.

**Comment by matyikriszta** [comment]
looks good to me now, @KimberleyCook are you happy to merge?

**Comment by jkbits1** [comment]
@samsworldofno this looks great

**Comment by KimberleyCook** [comment]
:+1:

**Pull request merged**
