### PR TITLE
Tutorial1 changes

### PR DESCRIPTION
**Pull request by andrewMacmurray**
@codebar @ladieswhocode made a few minor changes to text, added a few images, getting used to making pull requests!

### CODE REVIEW

**Comment by matyikriszta** [comment]
@andrewMacmurray looks good, one little request: can you remove 'popular' from 'JavaScript is a popular programming language'. Otherwise looks good!

**Comment by andrewMacmurray** [comment]
@matyikriszta thanks! have removed it.

**Comment by Charlotteis** [comment]
Looks great to me!

**Comment by matyikriszta** [comment]
thanks @andrewMacmurray

**Pull request merged**
