### PR TITLE
Replace use of 'join' function with 'implode'

### PR DESCRIPTION
**Pull request by bdsl**
If a student googles 'join' to learn more they'll just see that it's an alias of implode, and then have to read about implode. 
https://www.php.net/manual/en/function.join.php

Better to just use implode so there's one less step.

### CODE REVIEW

**Comment by bdsl** [comment]
FYI I wrote my own PHP tutorial a couple of years ago. I don't know how much interest your students have in PHP though. https://a-moderately-short-php-tutorial.com/

I can also recommend [Jon Duckett's book](https://www.goodreads.com/en/book/show/40985912-php-mysql), which is came out recently and covers modern PHP.

**Review by KimberleyCook — APPROVED** [review]
🎉

**Comment by KimberleyCook** [comment]
Thanks @bdsl

**Comment by bdsl** [comment]
That was quick! Thanks @KimberleyCook .

**Pull request merged**
