### PR TITLE
Add spaces to markdown headings

### PR DESCRIPTION
**Pull request by dwo**
I noticed the headings were appearing as, eg. `###HTTP Verbs` on http://tutorials.codebar.io/js/lesson4/tutorial.html when I was coaching last night.

### CODE REVIEW

**Comment by dwo** [comment]
I could also search the rest of the tutorials for this pattern and correct them. I wasn't sure if markdown is "supposed" to convert lines like `#Heading`, or if `# Heading` (with a space) is the only correct way. Daring Fireball's examples have the spaces: https://daringfireball.net/projects/markdown/syntax#header

**Comment by KimberleyCook** [comment]
@dwo Awesome spot thanks Rob. Just looked and it is on a few other ones too. I'll merge this in then if you want to do anymore I'll merge them in too :) 

Thanks very much

**Comment by KimberleyCook** [comment]
@dwo I just did this for lots of the tutorials, it was going to bug me if I didn't do it ha. Thanks for initially spotting it :D

**Comment by dwo** [comment]
No problems, I did another sweep and caught a few more in #277.

**Pull request merged**
