### PR TITLE
Includes url to Slack channel and amends domains

### PR DESCRIPTION
**Pull request by kaichanvong**
Increases clarity of domain names for chat rooms (gitter.im and slack.com – at time of writing).

### CODE REVIEW

**Comment by KimberleyCook** [comment]
@kaichanvong Can you amend and remove the Gitter URL completely please as we're trying to move away from it. Thanks

**Comment by kaichanvong** [comment]
OK. Done!

**Comment by deniseyu** [comment]
The Slack organisation cannot be joined directly at codebar.slack.com . People have to request an automatic invite first at http://codebar-slack.herokuapp.com . It's a pain, but it's because Slack wasn't designed for this purpose. Please include this link everywhere that Slack is currently linked to.

**Comment by kaichanvong** [comment]
Could you edit it for me please? Thank-yah

On 22 September 2015 at 18:23, Denise Yu <notifications@github.com> wrote:

> The Slack organisation cannot be joined directly at codebar.slack.com .
> People have to request an automatic invite first at
> http://codebar-slack.herokuapp.com . It's a pain, but it's because Slack
> wasn't designed for this purpose. Please include this link everywhere that
> Slack is currently linked to.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codebar/tutorials/pull/215#issuecomment-142355089>.
>



-- 
*Kai Chan Vong*
kai@kaivong.com

**Comment by despo** [comment]
Anyone has time to sort this issue so it can be merged? Thanks!

**Pull request closed without merging**
